-- MySQL Script generated by MySQL Workbench
-- Wed Mar 30 12:04:27 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Certificate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Certificate` (
  `idCertificate` INT NOT NULL,
  `Udělen` VARCHAR(45) NOT NULL,
  `Trvanlivost` DATE NOT NULL,
  PRIMARY KEY (`idCertificate`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Uživatel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Uživatel` (
  `id_name` INT NOT NULL,
  `F-name` VARCHAR(45) NOT NULL,
  `L-name` VARCHAR(45) NOT NULL,
  `Certificate_idCertificate` INT NOT NULL,
  PRIMARY KEY (`id_name`, `Certificate_idCertificate`),
  INDEX `fk_Uživatel_Certificate_idx` (`Certificate_idCertificate` ASC) VISIBLE,
  CONSTRAINT `fk_Uživatel_Certificate`
    FOREIGN KEY (`Certificate_idCertificate`)
    REFERENCES `mydb`.`Certificate` (`idCertificate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
